services:
  spigot-sales-webhook:
    build: .
    image: spigot-sales-webhook:local
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ./src/main/resources/config.yml:/opt/spigot-sales-webhook/config.yml:ro
      - ./data:/opt/spigot-sales-webhook/data
